-- ---------------------------------------------------------------------------
-- SalaryTontine - schema initial
-- Les contraintes d'integrite sont portees par la base et pas uniquement
-- par la couche Java.
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(120)   NOT NULL,
    email         VARCHAR(180)   NOT NULL,
    password_hash VARCHAR(100)   NOT NULL,
    role          VARCHAR(20)    NOT NULL,
    base_salary   NUMERIC(15, 2) NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ    NOT NULL,
    updated_at    TIMESTAMPTZ    NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('EMPLOYEE', 'MANAGER', 'ADMIN')),
    CONSTRAINT ck_users_base_salary_non_negative CHECK (base_salary >= 0)
);

CREATE TABLE tontines (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(120)   NOT NULL,
    monthly_amount NUMERIC(15, 2) NOT NULL,
    start_date     DATE           NOT NULL,
    status         VARCHAR(20)    NOT NULL,
    created_by     BIGINT         NOT NULL,
    created_at     TIMESTAMPTZ    NOT NULL,
    updated_at     TIMESTAMPTZ    NOT NULL,
    CONSTRAINT fk_tontines_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_tontines_status CHECK (status IN ('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_tontines_monthly_amount_positive CHECK (monthly_amount > 0)
);

CREATE TABLE tontine_members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tontine_id BIGINT      NOT NULL,
    user_id    BIGINT      NOT NULL,
    turn_order INTEGER     NOT NULL,
    joined_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_tontine_members_tontine FOREIGN KEY (tontine_id) REFERENCES tontines (id) ON DELETE CASCADE,
    CONSTRAINT fk_tontine_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_tontine_member_user UNIQUE (tontine_id, user_id),
    CONSTRAINT uk_tontine_member_turn_order UNIQUE (tontine_id, turn_order),
    CONSTRAINT ck_tontine_members_turn_order_min CHECK (turn_order >= 1)
);

CREATE TABLE contributions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tontine_id         BIGINT         NOT NULL,
    user_id            BIGINT         NOT NULL,
    amount             NUMERIC(15, 2) NOT NULL,
    contribution_month VARCHAR(7)     NOT NULL,
    status             VARCHAR(20)    NOT NULL,
    created_at         TIMESTAMPTZ    NOT NULL,
    CONSTRAINT fk_contributions_tontine FOREIGN KEY (tontine_id) REFERENCES tontines (id) ON DELETE CASCADE,
    CONSTRAINT fk_contributions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_contribution_tontine_user_month UNIQUE (tontine_id, user_id, contribution_month),
    CONSTRAINT ck_contributions_status CHECK (status IN ('PENDING', 'DEDUCTED', 'CANCELLED')),
    CONSTRAINT ck_contributions_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_contributions_month_format CHECK (contribution_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$')
);

CREATE TABLE salary_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT         NOT NULL,
    tontine_id        BIGINT         NOT NULL,
    salary_month      VARCHAR(7)     NOT NULL,
    base_salary       NUMERIC(15, 2) NOT NULL,
    tontine_deduction NUMERIC(15, 2) NOT NULL,
    tontine_received  NUMERIC(15, 2) NOT NULL,
    final_salary      NUMERIC(15, 2) NOT NULL,
    created_at        TIMESTAMPTZ    NOT NULL,
    CONSTRAINT fk_salary_records_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_salary_records_tontine FOREIGN KEY (tontine_id) REFERENCES tontines (id) ON DELETE CASCADE,
    CONSTRAINT uk_salary_record_user_month UNIQUE (user_id, salary_month),
    CONSTRAINT ck_salary_records_base_non_negative CHECK (base_salary >= 0),
    CONSTRAINT ck_salary_records_deduction_non_negative CHECK (tontine_deduction >= 0),
    CONSTRAINT ck_salary_records_received_non_negative CHECK (tontine_received >= 0),
    CONSTRAINT ck_salary_records_month_format CHECK (salary_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$')
);

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    action      VARCHAR(40)  NOT NULL,
    entity_type VARCHAR(60)  NOT NULL,
    entity_id   BIGINT,
    details     VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

-- Index de support des acces les plus frequents
CREATE INDEX idx_tontine_members_user ON tontine_members (user_id);
CREATE INDEX idx_tontines_status ON tontines (status);
CREATE INDEX idx_contributions_tontine_month ON contributions (tontine_id, contribution_month);
CREATE INDEX idx_contributions_user ON contributions (user_id);
CREATE INDEX idx_salary_records_user_month ON salary_records (user_id, salary_month);
CREATE INDEX idx_salary_records_tontine_month ON salary_records (tontine_id, salary_month);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at DESC);
