-- ---------------------------------------------------------------------------
-- SalaryTontine - V2
--   1. Le role MANAGER devient ACCOUNTANT (le comptable gere les tontines,
--      puisque la cotisation est un prelevement sur le salaire).
--   2. Les employes demandent eux-memes a rejoindre une tontine ouverte.
--
-- Une demande n'est PAS une participation : tant qu'elle n'est pas acceptee,
-- elle ne doit compter ni dans la cagnotte ni dans la duree du cycle. D'ou une
-- table distincte de tontine_members, qui reste la liste des seuls participants.
-- ---------------------------------------------------------------------------

ALTER TABLE users DROP CONSTRAINT ck_users_role;
UPDATE users SET role = 'ACCOUNTANT' WHERE role = 'MANAGER';
ALTER TABLE users ADD CONSTRAINT ck_users_role
    CHECK (role IN ('EMPLOYEE', 'ACCOUNTANT', 'ADMIN'));

CREATE TABLE tontine_join_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tontine_id   BIGINT      NOT NULL,
    user_id      BIGINT      NOT NULL,
    status       VARCHAR(20) NOT NULL,
    motivation   VARCHAR(300),
    decision_note VARCHAR(300),
    requested_at TIMESTAMPTZ NOT NULL,
    decided_at   TIMESTAMPTZ,
    decided_by   BIGINT,
    CONSTRAINT fk_join_requests_tontine FOREIGN KEY (tontine_id) REFERENCES tontines (id) ON DELETE CASCADE,
    CONSTRAINT fk_join_requests_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_join_requests_decided_by FOREIGN KEY (decided_by) REFERENCES users (id) ON DELETE SET NULL,
    -- Un employe n'a qu'une demande par tontine : une nouvelle tentative apres
    -- un refus reactive la ligne existante plutot que d'en creer une seconde.
    CONSTRAINT uk_join_request_tontine_user UNIQUE (tontine_id, user_id),
    CONSTRAINT ck_join_requests_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    -- Une decision porte toujours sa date et son auteur, ou aucun des deux.
    CONSTRAINT ck_join_requests_decision_complete CHECK (
        (status = 'PENDING' AND decided_at IS NULL AND decided_by IS NULL)
        OR (status <> 'PENDING' AND decided_at IS NOT NULL)
    )
);

CREATE INDEX idx_join_requests_tontine_status ON tontine_join_requests (tontine_id, status);
CREATE INDEX idx_join_requests_user_status ON tontine_join_requests (user_id, status);
