package com.salarytontine.enums;

/** Actions fonctionnelles tracees dans le journal d'audit. */
public enum AuditAction {
    TONTINE_CREATED,
    TONTINE_UPDATED,
    TONTINE_ACTIVATED,
    TONTINE_COMPLETED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_LEFT,
    TONTINE_CANCELLED,
    TONTINE_DELETED,
    CONTRIBUTIONS_GENERATED,
    SALARIES_GENERATED,
    USER_ROLE_UPDATED,
    USER_SALARY_UPDATED,
    USER_REGISTERED,
    USER_CREATED,
    USER_APPROVED,
    USER_REJECTED,
    USER_PASSWORD_CHANGED,
    JOIN_REQUESTED,
    JOIN_REQUEST_CANCELLED,
    JOIN_REQUEST_ACCEPTED,
    JOIN_REQUEST_REJECTED
}
